apiVersion: app.s3folder.com/v1alpha1
kind: FolderService
metadata:
  name: example-folderservice
  namespace: default
spec:
  userName: jai9
  userSecret:
    name: jai9-secret
  platformSecrets:
    aws:
      credentials:
        name: iam-secret