apiVersion: app.s3folder.com/v1alpha1
kind: FolderService
metadata:
  name: example-folderservice
  namespace: default
spec:
  userName: vivek1
  userSecret:
    name: vivek1-secret-1
  platformSecrets:
    aws:
      credentials:
        name: iam-secret