apiVersion: app.s3folder.com/v1alpha1
kind: FolderService
metadata:
  name: example-folderservice
  namespace: folder_namespace
spec:
  userName: vivek3
  userSecret:
    name: vivek3-secret
  platformSecrets:
    aws:
      credentials:
        name: iam-secret