apiVersion: app.s3folder.com/v1alpha1
kind: FolderService
metadata:
  name: example-folderservice
  namespace: default
spec:
  username: username
  userSecret:
    name: username-secret
  platformSecrets:
    aws:
      credentials:
        name: iam-secret
